name: Front-end CI

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci.yml'

jobs:
  node-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable corepack & install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies (monorepo)
        run: pnpm install --frozen-lockfile

      - name: Lint frontend
        run: pnpm --filter ./frontend lint

      - name: Run unit tests
        run: pnpm --filter ./frontend test --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: frontend/coverage