services:
  db:
    image: postgres:17
    container_name: projectname-db
    environment:
      POSTGRES_USER: projectname
      POSTGRES_PASSWORD: projectname_pw
      POSTGRES_DB: projectname_development
    volumes:
      # Persist data
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U projectname"]
      interval: 5s
      retries: 5
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: projectname-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"

volumes:
  db_data:
    driver: local